### PR TITLE
report BeginContact/EndContact for kinematic bodies

### PR DESCRIPTION
**Pull request by flyover**
#348

### CODE REVIEW

**Comment by erincatto** [comment]
Kinematic bodies do not collide.

**Comment by flyover** [comment]
It's convenient to use the same system for reporting the beginning and end of intersection for all shapes on all body types at the expense of the overhead only used by dynamic collisions.

Another suggestion was to pull b2Body::ShouldCollide out to the default b2ContactFilter.  Then, it could be modified as needed.

Perhaps even split each of the checks into functions, so they could still be used in the modified filters.  Something like:

```c++
bool b2ContactFilter::CheckBodyTypeDynamic(const b2Body& body, const b2Body& other);
bool b2ContactFilter::CheckJointsCollideConnected(const b2Body& body, const b2Body& other);
bool b2ContactFilter::CheckFilterGroup(const b2Fixture& fixture, const b2Fixture& other);
bool b2ContactFilter::CheckFilterCategoryMask(const b2Fixture& fixture, const b2Fixture& other);
```

Would you consider a PR for this?

**Comment by erincatto** [comment]
Please describe the game scenario you are trying to solve. There may be
another way to do it.

Thanks,
Erin

**Comment by flyover** [comment]
Perhaps using kinematic bodies for items bouncing around in a room with irregularly shaped walls, using the collision normal to modify the linear velocity.  Of course, all the API exists to do this externally; however, by using the system within Box2D, any callbacks (for sound effects, etc.) can be shared with that of dynamic bodies.

Thank you for taking the time to look at these PR's and, of course, the library itself.

**Comment by erincatto** [comment]
Okay, that sounds like a reasonable use case. I'll re-open this and review the changes.

**Pull request closed without merging**
