### PR TITLE
updating the premake5.lua to build on Ubuntu 16.04

### PR DESCRIPTION
**Pull request by ZenToad**
I did have to change some paths and two nullptr variables to NULL.

### CODE REVIEW

**Comment by erincatto** [comment]
Awesome! The make files should not be in the repo. I expect people to run premake and generate the make files. Please try getting g++ to run in C++11 mode: http://stackoverflow.com/questions/10363646/compiling-c11-with-g

**Comment by ZenToad** [comment]
Will do.  Thanks for the link.

**Comment by ZenToad** [comment]
I should have merge all the changes, removed all the build files, and fix the c++11 stuff

**Comment by ZenToad** [comment]
Please check this out an let me know if anything need updating.

**Comment by erincatto** [comment]
Thanks, does nullptr work with the C++11 flag? If so, you can revert those files with nullptr.

**Comment by ZenToad** [comment]
You got it. I just figured because there are other pointers that all use
NULL and they aren't all nullptr that is was a mistake. But not a big deal.

**Pull request merged**
