### PR TITLE
Merge Liquidfun into Box2D

### LINKED ISSUE #370: Merge liquidfun in with Box2D
Box2D is being maintained, while [liquidfun](https://github.com/google/liquidfun) doesn't appear to be; yet liquidfun adds a whole bunch of features to Box2D.

I can do this if you'd like.

### PR DESCRIPTION
**Pull request by JesseTG**
Fix #370 
Fix #369 

This adds the particle system that Liquidfun introduces, plus associated testbeds.

Additionally:

- Unit tests added (courtesy of Liquidfun)
- Update to latest glfw
- Fix bugs/compilation errors with revised testbed

Only thing I still need to do is draw particles in the testbed, so not quite ready for a merge yet.

### CODE REVIEW

**Comment by erincatto** [comment]
Sorry for the misunderstanding. I just updated the Readme.md:

The main Box2D library is open source, but not open contribution. Please do not submit pull requests. Exceptions may be considered for build files and other items that are not part of the main library source. Thank you for your understanding.

**Comment by JesseTG** [comment]
I'm sorry, but no, I don't understand.  May I ask about your reasoning?

**Comment by erincatto** [comment]
Some open source projects are a community efforts and some are personal projects. Box2D is a personal project that I happen to share freely.

**Comment by JesseTG** [comment]
What about the fact that I properly resolved #360?  Do you want me to pick those out and submit those commits separately?  (The issue is that glfw uses CMake to customize certain headers, so you can't just stick in a bunch of source and header files and expect it to compile everywhere.)

**Comment by erincatto** [comment]
I will integrate bug fixes and build fixes soon. Thanks.

**Pull request closed without merging**
