### PR TITLE
Revert C11 compilation requirement

### PR DESCRIPTION
**Pull request by dagostinelli**

### CODE REVIEW

**Comment by chapterjason** [comment]
+1

**Comment by richardeigenmann** [comment]
Using nullptr on line 216 of b2Body.cpp appears to be C++11 which will not compile on older standards. 

Whilst it is important for a library to remain usable in older applications time does move on and eventually upgrades should be made by all to the latest current standard. Teams with a valid reason to stay behind can continue to use the old versions of the library.

I would vote to add the following line to the main CMakeLists.txt and keep the nullptr:
set (CMAKE_CXX_STANDARD 11)

But if compatibility with C++ from 10 years ago is a huge issue let's just approve this pull request and leave it up to the users of the library if they want to use C++11 or not.

I found the views of Bjarne interesting that are quoted in this article: <http://stackoverflow.com/questions/20509734/null-vs-nullptr-why-was-it-replaced>

**Comment by louis-langholtz** [comment]
Please note that `nullptr` made it into other files also. See `Box2D/Testbed/Framework/Main.cpp` for another instance. This pull request only addresses the C++11 `nullptr` in `Box2D/Box2D/Dynamics/b2Body.cpp` however.

**Comment by erincatto** [comment]
I plan to use C++11 for other things, like override. If you cannot support C++11, I recommend making a fork.

**Pull request closed without merging**
