### PR TITLE
Linux gcc fixes

### LINKED ISSUE #774: `BUILD_BENCHMARKS=ON` fails
I'm trying to build this project with `BUILD_BENCHMARKS=ON`.  I'm using GCC 14 with Ubuntu 24.04 LTS.  This is the exact compilation output:

```
[ 89%] Building C object benchmark/CMakeFiles/benchmark.dir/main.c.o
cd /home/ben/Projects/box2d/build_gcc/benchmark && /usr/bin/gcc-14 -DENKITS_TASK_PRIORITIES_NUM=3 -I/home/ben/Projects/box2d/src/../include -I/home/ben/Projects/box2d/build_gcc/src -I/home/ben/Projects/box2d/build_gcc/_deps/enkits-src/src -I/home/ben/Projects/box2d/extern/simde -O3 -DNDEBUG -std=c17 -Werror -MD -MT benchmark/CMakeFiles/benchmark.dir/main.c.o -MF CMakeFiles/benchmark.dir/main.c.o.d -o CMakeFiles/benchmark.dir/main.c.o -c /home/ben/Projects/box2d/benchmark/main.c
/home/ben/Projects/box2d/benchmark/main.c: In function ‘GetNumberOfCores’:
/home/ben/Projects/box2d/benchmark/main.c:65:14: error: expected expression before ‘return’
   65 |         (int)return sysconf( _SC_NPROCESSORS_ONLN );
      |              ^~~~~~
```

I checked out tag `v3.0.0` and tried building off of that.

### PR DESCRIPTION
**Pull request by erincatto**
Fixes #774 and more.

Added Intel N100 benchmarks.

### CODE REVIEW

**Comment by terroo** [comment]
Take advantage and include `cstdio` in the file: `samples/sample_determinism.cpp` as there is an error when compiling due to the lack of this header.

**Comment by erincatto** [comment]
> Take advantage and include `cstdio` in the file: `samples/sample_determinism.cpp` as there is an error when compiling due to the lack of this header.

This pull requests already adds <stdio.h> to that file. I was able to compile and run the samples on ubuntu.

**Comment by define-private-public** [comment]
Thanks for doing this.  I'm looking to do some benchmarking of C & C++ language features and I thought using Box2D would be good since it's a more real-world application/library.

Can the benchmarks be run in a headless mode?

**Comment by erincatto** [comment]
> Thanks for doing this. I'm looking to do some benchmarking of C & C++ language features and I thought using Box2D would be good since it's a more real-world application/library.
> 
> Can the benchmarks be run in a headless mode?

Yes, the benchmark application runs on the console and emits csv files.

**Pull request merged**
