### PR TITLE
FAQ - "provides" instead of "proves" wording

### PR DESCRIPTION
**Pull request by mreinstein**

### CODE REVIEW

**Comment by erincatto** [comment]
Thanks for fix. This is in #829

**Comment by mreinstein** [comment]
Not that I care about "getting credit" for a basic typo PR in github, but I'm curious why you're opposed to merging PRs from contributors directly.  Is there a specific process that this interferes with?

**Comment by erincatto** [comment]
I want to avoid dealing with https://en.wikipedia.org/wiki/Contributor_License_Agreement

**Comment by erincatto** [comment]
Additionally, I almost always take fixes from small PRs. So they are still worthwhile even if they are not merged directly.

**Comment by amytimed** [comment]
> I want to avoid dealing with https://en.wikipedia.org/wiki/Contributor_License_Agreement

https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#6-contributions-under-repository-license:
> Whenever you add Content to a repository containing notice of a license, you license that Content under the same terms, and you agree that you have the right to license that Content under those terms. If you have a separate agreement to license that Content under different terms, such as a contributor license agreement, that agreement will supersede.

CLA isnt needed for PR contributions to be licensed MIT and usable in the repo

**Comment by erincatto** [comment]
I'm not concerned about the MIT license. I'm concerned about the copyright.

**Comment by mreinstein** [comment]
I don't pretend to be a lawyer but I would think given that people are putting records of changes into public forums, contributions could still be traced to other people, even if the actual commits a given repo are solely through your username. It seems like a more labor intensive way of working that doesn't offer any additional defense against "external" contributors. 🤷

**Comment by mreinstein** [comment]
e.g., someone submits a PR containing truly meaningful (non-typo :) ) changes. Those changes then get put into a subsequent commit to box2d under your username....if someone wanted to make a copyright claim (this seems unlikely to me but possible I suppose) the evidence of their changes going into the codebase and being a contributor to intellectual property is there plain as day, right?

**Comment by erincatto** [comment]
I look at it like writing a book. Someone can give you comments, feedback, and indicate typos and grammar problems. But they should not be writing or changing the book or they will also be an author of the book.

I'm not stating this as something legal. I'm just describing the Box2D development process.

**Comment by mreinstein** [comment]
> I look at it like writing a book. Someone can give you comments, feedback, and indicate typos and grammar problems. But they should not be writing or changing the book or they will also be an author of the book.

That's an interesting metaphor, but I wonder if that works for books because usually there's no neutral 3rd party that records those conversations and feedback. In the case of github, someone could easily point to conversations leading up to a PR and the PR itself as proof that "hey I contributed to box2d, whether the code went directly into the release from my account, or through Erin's account".   Again I don't pretend to be a lawyer or really understand this stuff; from my perspective that was just my impression.  I wouldn't think this would actually protect against people laying claim to ownership via contribution.  Said differently I don't know if there's a way around dealing with setting up a CLA if that's really a concern.  


> I'm not stating this as something legal. I'm just describing the Box2D development process.

Yeah fair.  I'm not judging, just genuinely curious about the process/reasoning.

**Pull request closed without merging**
