### PR TITLE
Improve user settings capability.

### PR DESCRIPTION
**Pull request by 1aam2am1**
Because I was implementing my own allocator, who had static store duration, i needed cpp file to be added to build process.

### CODE REVIEW

**Comment by erincatto** [comment]
Are you using Box2D as a shared library (DLL)? If not, can you use extern?

**Comment by 1aam2am1** [comment]
I'm using it as shared library. Therefore extern won't work.

**Comment by erincatto** [comment]
Why are you using it as a shared library?

**Comment by 1aam2am1** [comment]
It is faster on build time. I need to rebuild my program each time I change something. With shared library linker is faster as it don't need check if all symbols exists and connect them.

**Comment by erincatto** [comment]
How much faster is linking that way? How about the overhead of loading the shared library when you launch? Box2D is a smallish library.

**Comment by erincatto** [comment]
I'm not happy supporting box2d as a shared library. Too much feature creep. I would rather work on simulation and features and not build system stuff.

**Pull request closed without merging**
