### PR TITLE
fix armeabi-v7a

### PR DESCRIPTION
**Pull request by bostick**
Fix https://github.com/erincatto/box2d/issues/813

Emulate vzip1q_f32 for 32-bit

### CODE REVIEW

**Comment by erincatto** [comment]
Thanks for this fix! Are you able to do any performance comparisons versus SIMD disabled on this platform? Just curious.

**Comment by bostick** [comment]
I have a 32-bit arm7 device I can test on. What comparisons would be good to do?

**Comment by erincatto** [comment]
If you can run the benchmark app that would be great.

https://github.com/erincatto/box2d/blob/2dbb6818cb5e69bd3dcd20b7190cdba3844dd4e8/CMakeLists.txt#L72

**Comment by bostick** [comment]
OK, I will setup a simple Android app for running the benchmark.

**Comment by bostick** [comment]
OK @erincatto , I put up a repo with the results of running the benchmark:
https://github.com/bostick/Box2DAndroidBenchmark

I have not interpreted the results. Let me know if you'd like anything else

**Comment by erincatto** [comment]
image

It seems SIMD optimizations are not helping on this CPU. I've heard 32-bit Neon is not very good. I see good results on 64-bit Neon though. This CPU is also quite slow in general. But it does make sense to use around 4 threads on this.

Thanks a lot for running these tests!

**Comment by bostick** [comment]
Ah, I messed up the formatting when I stripped the `\n` in the `fprintf` calls when I was replacing all of `printf` calls with Android logging. Fixed in the repo now.

**Pull request closed without merging**
