### PR TITLE
some modification on CMakeList.txt files 

### PR DESCRIPTION
**Pull request by njuFerret**
1. add `make install` command to CMakeLists.txt, rename `samples` as ` testbed`
2. put `extern` folder under `samples` for testbed samples built standalone 
3. add conditional include for mingw build under windowns in `samples/main.cpp`
4. recover `GetVertexCount` and `GetVertex` functions in `b2_polygon_shape.h` for compatable purpose
5. modification tested only under Win10x64 with MinGW 7.3.0 x64

### CODE REVIEW

**Comment by erincatto** [comment]
A lot of these changes are subjective and are not accepted:
- samples rename
- moving extern
- unnecessary accessors (all members are public)
- white space

**Comment by njuFerret** [comment]
got it, 
If there's a guideline for PR maybe better.
thanks for this great project

**Comment by njuFerret** [comment]
fine, thanks for this great project

**Comment by erincatto** [comment]
By the way, I did rename samples back to testbed mainly because it makes it easier to document.

**Pull request closed without merging**
