### PR TITLE
Fixed build to use C++11 flag for MinGW/GCC

### PR DESCRIPTION
**Pull request by trid**
This fixes the problem with nullptr in code for MinGW/GCC compilers.

### CODE REVIEW

**Comment by dagostinelli** [comment]
I like the fix in #412 better because it keeps Box2D from requiring a higher C++ standard than absolutely necessary.

**Comment by CaffeineViking** [comment]
Agreed, @dagostinelli has a very good point. Since this is the only location where `nullptr` was being used, there really is no need to transition to C++11 right now (since it serves little to no practial purpose right now). Perhaps later when the author commits to transition the library to C++11, this could be done.

**Comment by onlycxue** [comment]
nice

**Comment by felaugmar** [comment]
I'm already targeting c++14,
so I'm using this one.

But, for most projects the #412 is better,
#412 is a better choice for being pulled, in my guess.

**Comment by erincatto** [comment]
I plan to use other C++11 features such as override. If you cannot use C++11 please make a fork. Thank you.

**Pull request closed without merging**
