### PR TITLE
Add userdata setters back

### PR DESCRIPTION
**Pull request by thegrb93**

### CODE REVIEW

**Comment by thegrb93** [comment]
They don't work with void* though which breaks compatibility. The only solution I could think of was `body->SetUserData(*(b2BodyUserData*)(&udata))`

**Comment by erincatto** [comment]
Setters are no longer needed. See #659

**Comment by thegrb93** [comment]
Allright, thanks.

**Comment by thegrb93** [comment]
Looks like for other types, I could do body->GetUserData() = udata as well.

**Comment by thegrb93** [comment]
@erincatto there's still a signature for SetUserData in b2Body you might want to get rid of.

**Comment by marauder2k7** [comment]
This doesn't seem to work anymore? are there any examples of b2_user_settings that shows how to add custom userdata?

**Pull request closed without merging**
