### PR TITLE
support older versions of GLSL

### PR DESCRIPTION
**Pull request by flyover**
Tested:
Linux Mint 18.3; OpenGL 3.0 Mesa 17.2.8, GLSL 1.30

### CODE REVIEW

**Comment by flyover** [comment]
Hold on.  This breaks Mac OSX.

**Comment by flyover** [comment]
Ok, Mac OSX is fixed.  Switched back to OpenGL 2.1.

**Comment by erincatto** [comment]
Why do you want this change?

**Comment by flyover** [comment]
I use this branch on an old Sony laptop running Linux.  I thought others might find it useful.

**Comment by erincatto** [comment]
Thanks, but I don't intend to support older platforms in the testbed. The main library should work fine on older platforms.

**Pull request closed without merging**
