### PR TITLE
mac os crash fix

### PR DESCRIPTION
**Pull request by ccworld1000**
mac os crash fix

### CODE REVIEW

**Comment by ccworld1000** [comment]
mac os crash fix

**Comment by erincatto** [comment]
Please read here about running in xcode:
https://github.com/erincatto/Box2D/blob/master/Building.md

**Comment by ccworld1000** [comment]
yes , i use 'premake5 xcode4'

Can you tag the new version and support the latest podfile

**Comment by erincatto** [comment]
Did you follow these steps:
"Edit the Testbed Scheme, in the Run Options, use a custom working directory
Set the Testbed directory as the working directory"

**Comment by ccworld1000** [comment]
sorry, Forget to set options

**Comment by ccworld1000** [comment]
Can you tag the new version and support the latest podfile?

**Comment by ccworld1000** [comment]
Now the Xcode version is 10.1. You use 4. Do you want to change this piece?

**Pull request closed without merging**
