### PR TITLE
Misc Issues

### PR DESCRIPTION
**Pull request by erincatto**
- renamed smooth segment to chain segment
- addressed several minor issues

#777
#779
#754 
#749 
#782 
#781 
#776

### CODE REVIEW

**Comment by mathisloge** [comment]
@erincatto I've also noticed, that no CMake Config is installed. 
That would be missing, too.

**Comment by erincatto** [comment]
> @erincatto I've also noticed, that no CMake Config is installed. That would be missing, too.

I added a bunch of config stuff I had in 2.4. No idea how this stuff works.

**Comment by mathisloge** [comment]
I can check it tomorrow 👍

**Comment by mathisloge** [comment]
@erincatto I've tested it at it works like before.
So good for me this one 👍

**Comment by erincatto** [comment]
> @erincatto I've tested it at it works like before. So good for me this one 👍

Thanks for your assistance!

**Pull request merged**
