### PR TITLE
What about CMake?

### PR DESCRIPTION
**Pull request by andrejlevkovitch**
I add cmake support. Now you can build and install it by cmake, and, of cause, can use find_package in other cmake scripts.

### CODE REVIEW

**Comment by andrejlevkovitch** [comment]
Also, you can use this as git submodule and just use add_subdir in CMakeLists.txt

**Comment by bigdavedev** [comment]
What is the status of this PR? It would be nice to see CMake in master and this PR is a by-the-book example. It will make integration with other projects very simple.

**Comment by andrejlevkovitch** [comment]
Unfortunately I have not complete example of usage, but it very simple: just call `add_subdirectory(Box2d)` in you `CMakeLists.txt` and use target Box2d - that's all

**Comment by bigdavedev** [comment]
> 
> 
> Unfortunately I have not complete example of usage, but it very simple: just call `add_subdirectory(Box2d)` in you `CMakeLists.txt` and use target Box2d - that's all

Thanks for that explanation, but that was not what I was asking for :)

I was asking about whether or not this will be merged to master anytime soon, so that I can migrate from my own fork back to upstream. My CMake integration is almost identical to yours (`OBJECT` libraries and a shared/static lib), but I have not done any of the install/packaging stuff that you have as it was not a requirement.

**Comment by erincatto** [comment]
Box2D now uses cmake.

**Pull request closed without merging**
