### PR TITLE
Fix CMake build for Testbed on linux (updated)

### PR DESCRIPTION
**Pull request by ilya-kolpakov**
Fixes a minor issue in PR #435: autogenerated `glfw_config.h` was put in a source dir instead of the build dir.

### CODE REVIEW

**Comment by ilya-kolpakov** [comment]
I also deleted static `glfw_config.h` as I assume it should be always produced from `glfw_config.h.in`

**Comment by ettoretorti** [comment]
These changes will break the build on windows. The build there does not autogenerate anything, and expects glfw_config.h to be in the source dir. Generating glfw_config.h into the source dir was intentional as a workaround.

**Comment by ilya-kolpakov** [comment]
I reverted the static `glfw_config.h` and fixed its location to be the source dir. With this commit `make Box2D` target works on my Linux machine provided one fixes #438. There are further issues with `make testbed` though.

**Comment by ilya-kolpakov** [comment]
To build the Testbed successfully on Linux one has to fix "Box2D/glew/glxew.h" as following

https://github.com/ilya-kolpakov/Box2D/commit/64b752ccbb2ed9936f0a25116cef9ced3984e9fb#diff-0b08c251c6162ed1001dbaaf29eed0f1

Would it create problems for Windows build?

**Comment by erincatto** [comment]
Old issue. Box2D now uses Premake5 to build the testbed. Note that buiding the testbed is optional. See Building.txt for more details

**Pull request closed without merging**
